spring:
  datasource:
    url: jdbc:mysql://119.23.31.13:3306/quartz?useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity

logging:
  level:
    com.example.demo.dao : debug